### ISSUE TITLE
How to not persist certain reducers?

### ISSUE THREAD

**Issue by wizevlad** [ryanwillis/redux-persist-capacitor#1]
Hi, thanks for this package.

Do you know how to persist only certain slices? I have a `global` slice and others, and I only want to persist global.

**Comment by ryanwillis** [comment]
You can include or exclude slices via the [whitelist/blacklist](https://github.com/ryanwillis/reduxjs-toolkit-persist#blacklist--whitelist) config options.

**Comment by ryanwillis** [comment]
@wizevlad did this answer your question? If so, I will close this issue.

**Comment by ryanwillis** [comment]
Closing issue.
